database: 
  - name: sample_app
    databaseName: sample_app_for_backend_production
    user: sample_app_for_backend

services: 
  - type: web
    name: Sample App
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sample_app_for_backend_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false